name: diffdock_pp
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.8
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - numpy
  - dill
  - tqdm
  - pyyaml
  - pandas
  - scikit-learn
  - biopython
  - matplotlib
  - pip:
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - torch-cluster
    - torch-spline-conv
    - torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu116.html
    - e3nn
    - wandb
    - tensorboard
    - tensorboardX
    - biopandas

